### Generate OTP
GET http://localhost:8080/api/totp-code
Content-Type: application/json

### Validate OTP
POST http://localhost:8080/api/totp-validate
Content-Type: application/json

{
  "otpSecret": "KMKR7FVLKQGOVECXKBOYZOEFUJ5VTLZQ",
  "otpCode": "123"
}